"use client";
import { useEffect,useMemo,useState } from "react";
import { Activity, Apple, BarChart3, Dumbbell, Home, LogOut, Plus, Settings, TrendingUp, X } from "lucide-react";
import { Logo } from "./logo";

type Dash={profile:{name:string;weightKg:number};summary:{consumed:number;exercise:number;maintenance:number;target:number;balance:number;protein:number;carbs:number;fat:number;proteinTarget:number;carbsTarget:number;fatTarget:number};foods:any[];workouts:any[];weightTrend:any[]};
const today=()=>new Date().toISOString().slice(0,10);
export function AppShell(){
 const [view,setView]=useState('Hoje');const [data,setData]=useState<Dash|null>(null);const [modal,setModal]=useState<'food'|'workout'|'weight'|null>(null);const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);const r=await fetch('/api/dashboard?date='+today(),{cache:'no-store'});if(r.status===401){location.href='/login';return}const d=await r.json();setData(d);setLoading(false)}
 useEffect(()=>{load()},[]);
 const nav=[['Hoje',Home],['Alimentação',Apple],['Treinos',Dumbbell],['Progresso',TrendingUp]] as const;
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/'}
 return <div className="min-h-screen bg-[#f6f8f7]">
  <aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-[#e2eae8] bg-white p-5 lg:block"><Logo/><nav className="mt-9 space-y-1">{nav.map(([n,I])=><button key={n} onClick={()=>setView(n)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${view===n?'bg-[#e7f3ee] text-[#145c5a]':'text-[#647673] hover:bg-[#f4f7f6]'}`}><I size={18}/>{n}</button>)}</nav><div className="absolute bottom-5 left-5 right-5"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-[#647673] hover:bg-[#f4f7f6]"><Settings size={18}/>Configurações</button><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-[#8a5b5b] hover:bg-red-50"><LogOut size={18}/>Sair</button></div></aside>
  <main className="pb-24 lg:ml-64 lg:pb-8"><header className="sticky top-0 z-20 border-b border-[#e3ebe8] bg-[#f6f8f7]/90 px-5 py-4 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between"><div className="lg:hidden"><Logo compact/></div><div><p className="hidden text-xs font-black uppercase tracking-[.18em] text-[#7f918e] lg:block">Forma</p><h1 className="text-xl font-black tracking-tight">{view}</h1></div><div className="flex gap-2"><button onClick={()=>setModal('food')} className="btn-secondary hidden sm:inline-flex items-center gap-2"><Plus size={16}/>Refeição</button><button onClick={()=>setModal('workout')} className="btn-primary inline-flex items-center gap-2"><Plus size={16}/>Treino</button></div></div></header>
  <div className="mx-auto max-w-6xl px-5 py-6 sm:px-8">{loading||!data?<div className="card p-10 text-center text-[#6f817e]">Carregando seu painel...</div>:<View name={view} data={data} setModal={setModal}/>}</div></main>
  <nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-4 border-t border-[#dfe8e5] bg-white px-2 py-2 lg:hidden">{nav.map(([n,I])=><button key={n} onClick={()=>setView(n)} className={`grid place-items-center gap-1 rounded-xl py-2 text-[11px] font-bold ${view===n?'text-[#145c5a]':'text-[#7d8d8a]'}`}><I size={19}/>{n}</button>)}</nav>
  {modal&&<EntryModal type={modal} close={()=>setModal(null)} done={()=>{setModal(null);load()}} weight={data?.profile.weightKg||50}/>} </div>
}
function Ring({value,max,label}:{value:number;max:number;label:string}){const p=Math.min(100,Math.round(value/max*100||0));return <div><div className="mb-1 flex justify-between text-xs font-bold"><span>{label}</span><span>{Math.round(value)} / {Math.round(max)} g</span></div><div className="h-2 rounded-full bg-[#e8efed]"><div className="h-2 rounded-full bg-[#145c5a]" style={{width:p+'%'}}/></div></div>}
function View({name,data,setModal}:{name:string;data:Dash;setModal:(x:any)=>void}){const s=data.summary;
 if(name==='Hoje')return <div className="space-y-5"><section className="grid gap-4 md:grid-cols-3">{[["Consumidas",s.consumed,"kcal"],["Gasto estimado",s.maintenance,"kcal"],["Saldo",s.balance,"kcal"]].map(([l,v,u]:any)=><div className="card p-5" key={l}><p className="text-xs font-black uppercase tracking-[.15em] text-[#82928f]">{l}</p><div className="mt-2 kpi-number text-4xl font-black">{Math.round(v)}</div><p className="mt-1 text-xs text-[#7f918e]">{u}</p></div>)}</section><section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="card p-6"><div className="flex justify-between"><div><p className="text-sm font-black text-[#145c5a]">Meta do dia</p><h2 className="mt-1 text-2xl font-black">{Math.round(s.target)} kcal</h2></div><span className="h-fit rounded-full bg-[#e3f3ec] px-3 py-1 text-xs font-black text-[#145c5a]">estimativa</span></div><div className="mt-6 space-y-4"><Ring value={s.protein} max={s.proteinTarget} label="Proteína"/><Ring value={s.carbs} max={s.carbsTarget} label="Carboidratos"/><Ring value={s.fat} max={s.fatTarget} label="Gorduras"/></div></div><div className="card p-6"><p className="text-sm font-black">Ações rápidas</p><div className="mt-4 grid gap-3"><button onClick={()=>setModal('food')} className="btn-secondary text-left">+ Registrar refeição</button><button onClick={()=>setModal('workout')} className="btn-secondary text-left">+ Registrar treino</button><button onClick={()=>setModal('weight')} className="btn-secondary text-left">+ Atualizar peso</button></div><p className="mt-4 text-xs leading-5 text-[#80918e]">O gasto de exercício é estimado por MET e peso corporal. Use a tendência de semanas como referência principal.</p></div></section></div>;
 if(name==='Alimentação')return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e7eeec] p-5"><div><h2 className="text-xl font-black">Refeições de hoje</h2><p className="text-sm text-[#768885]">{data.foods.length} itens registrados</p></div><button onClick={()=>setModal('food')} className="btn-primary">+ Adicionar</button></div>{data.foods.length?data.foods.map((f:any)=><div key={f.id} className="grid grid-cols-[1fr_auto] gap-4 border-b border-[#edf2f0] p-5"><div><p className="font-black">{f.name}</p><p className="mt-1 text-xs text-[#7d8e8b]">{f.mealType} · {f.quantity} {f.unit}</p></div><div className="text-right"><p className="font-black">{Math.round(+f.calories)} kcal</p><p className="text-xs text-[#7d8e8b]">P {Math.round(+f.protein)} · C {Math.round(+f.carbs)} · G {Math.round(+f.fat)}</p></div></div>):<Empty icon={Apple} text="Nenhuma refeição registrada hoje."/>}</section>;
 if(name==='Treinos')return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e7eeec] p-5"><div><h2 className="text-xl font-black">Treinos de hoje</h2><p className="text-sm text-[#768885]">{Math.round(s.exercise)} kcal de exercício estimadas</p></div><button onClick={()=>setModal('workout')} className="btn-primary">+ Adicionar</button></div>{data.workouts.length?data.workouts.map((w:any)=><div key={w.id} className="flex items-center justify-between border-b border-[#edf2f0] p-5"><div><p className="font-black">{w.type}</p><p className="text-xs text-[#7d8e8b]">{w.durationMinutes} min · {w.intensity}</p></div><div className="text-right font-black">≈ {Math.round(+w.caloriesEstimated)} kcal</div></div>):<Empty icon={Dumbbell} text="Nenhum treino registrado hoje."/>}</section>;
 return <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="card p-6"><h2 className="text-xl font-black">Evolução de peso</h2><p className="mt-1 text-sm text-[#758783]">Últimos registros</p><div className="mt-6 flex h-48 items-end gap-2">{data.weightTrend.length?data.weightTrend.map((x:any,i:number)=>{const vals=data.weightTrend.map((z:any)=>+z.weightKg);const mn=Math.min(...vals)-.5,mx=Math.max(...vals)+.5;const h=25+((+x.weightKg-mn)/(mx-mn||1))*70;return <div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-lg bg-[#79b9a2]" style={{height:h+'%'}}/><span className="text-[10px] font-bold text-[#748683]">{+x.weightKg}</span></div>}):<p className="m-auto text-sm text-[#7a8c89]">Registre seu peso para ver a tendência.</p>}</div></section><section className="card p-6"><p className="text-sm font-black text-[#145c5a]">Peso atual</p><div className="mt-2 kpi-number text-5xl font-black">{data.profile.weightKg}<span className="ml-1 text-lg">kg</span></div><button onClick={()=>setModal('weight')} className="btn-primary mt-6 w-full">Atualizar peso</button></section></div>}
function Empty({icon:Icon,text}:{icon:any;text:string}){return <div className="grid place-items-center gap-3 p-12 text-center text-[#7c8d8a]"><Icon size={28}/><p className="text-sm">{text}</p></div>}
function EntryModal({type,close,done,weight}:{type:'food'|'workout'|'weight';close:()=>void;done:()=>void;weight:number}){const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const body=Object.fromEntries(new FormData(e.currentTarget).entries());const url=type==='food'?'/api/meals':type==='workout'?'/api/workouts':'/api/progress';const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,logDate:today(),weightKg:type==='weight'?body.weightKg:undefined,currentWeightKg:weight})});setBusy(false);if(r.ok)done()}
 return <div className="fixed inset-0 z-50 grid place-items-end bg-black/30 p-0 sm:place-items-center sm:p-5"><div className="w-full max-w-lg rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">{type==='food'?'Adicionar refeição':type==='workout'?'Registrar treino':'Atualizar peso'}</h2><button onClick={close} className="rounded-xl p-2 hover:bg-[#f1f5f3]"><X size={19}/></button></div><form onSubmit={submit} className="grid gap-3">
 {type==='food'&&<><input className="input" name="name" placeholder="Alimento ou refeição" required/><select className="input" name="mealType"><option>Café da manhã</option><option>Lanche</option><option>Almoço</option><option>Jantar</option><option>Ceia</option></select><div className="grid grid-cols-2 gap-3"><input className="input" name="quantity" type="number" step=".1" placeholder="Quantidade" defaultValue="1"/><input className="input" name="unit" placeholder="Unidade" defaultValue="porção"/></div><input className="input" name="calories" type="number" step=".1" placeholder="Calorias" required/><div className="grid grid-cols-3 gap-2"><input className="input" name="protein" type="number" step=".1" placeholder="Proteína"/><input className="input" name="carbs" type="number" step=".1" placeholder="Carbo"/><input className="input" name="fat" type="number" step=".1" placeholder="Gordura"/></div></>}
 {type==='workout'&&<><select className="input" name="type"><option>Musculação</option><option>Jiu-jitsu</option><option>Muay Thai</option><option>Corrida</option><option>Caminhada</option><option>Outro</option></select><input className="input" name="durationMinutes" type="number" placeholder="Duração em minutos" required/><select className="input" name="intensity"><option value="moderate">Moderada</option><option value="light">Leve</option><option value="high">Alta</option></select></>}
 {type==='weight'&&<input className="input" name="weightKg" type="number" step=".1" defaultValue={weight} required/>}
 <button disabled={busy} className="btn-primary mt-2 w-full">{busy?'Salvando...':'Salvar'}</button></form></div></div>}
